parameters :\n    database_host: 
    database_port: 
    database_name: 
    database_user: 
    database_password: 
    mailer_transport: smtp    mailer_host: 
    mailer_user: null    mailer_password: null    secret: null    secret: a37bbe4372b18dc6977b831e9e6be5e0ff8d7e6e