<?php

namespace MQ\QuiziBundle\Entity;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends \Doctrine\ORM\EntityRepository
{




}
